openapi: '3.0.3'
info:
  title: music-collab-playlist-api
  description: OpenAPI specification for Collaborative music playlist handler
  version: 1.1.0

servers:
  - url: 'http://127.0.0.1:8080'
    description: Local Spring Boot Server

components:
  securitySchemes:
    JSESSIONIDAuth:
      type: apiKey
      in: cookie
      name: JSESSIONID

security:
  - JSESSIONIDAuth: []

paths:
  /api/dashboard:
    get:
      tags:
        - Dashboard
      operationId: getDashboardSettings
      description: get dashboard settings for user
      summary: Get dashboard settings
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './model/dashboard-settings.yaml'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /api/dashboard/name:
    post:
      tags:
        - Dashboard
      operationId: setName
      description: modify suggestion playback settings for user
      summary: Modify suggestion playback settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './request/modify-name-req.yaml'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './response/modify-name-resp.yaml'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /api/dashboard/suggestion-playback:
    post:
      tags:
        - Dashboard
      operationId: setSuggestionPlayback
      description: modify suggestion playback settings for user
      summary: Modify suggestion playback settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './request/modify-suggestion-playback-mode-req.yaml'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './enum/suggestion-playback-mode.yaml'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /api/dashboard/youtube-playback:
    post:
      tags:
        - Dashboard
      operationId: setYoutubePlayback
      description: modify youtube playback settings for user
      summary: Modify youtube playback settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './request/modify-youtube-playback-mode-req.yaml'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './enum/youtube-playback-mode.yaml'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /api/dashboard/regenerate-code:
    post:
      tags:
        - Dashboard
      operationId: regenerateDeviceCode
      summary: Regenerate the unique 6-digit device code (server creates new code)
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './response/regenerate-code-resp.yaml'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /join-playlist:
    post:
      tags:
        - Join
      operationId: joinPlaylist
      summary: Join a playlist by providing the current playlist name and code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './request/join-playlist-req.yaml'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './response/join-playlist-resp.yaml'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /search:
    post:
      tags:
        - Search
      operationId: searchMusic
      summary: Search Spotify or YouTube for tracks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './request/search-req.yaml'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './model/track-summary.yaml'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /suggest-track:
    post:
      tags:
        - Suggest
      operationId: suggestTrack
      summary: Suggest a track for the joined playlist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './request/suggest-track-req.yaml'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './model/playlist.yaml'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /handle-playlist/search:
    post:
      tags:
        - Search
      operationId: searchAsOwner
      summary: Search Spotify or YouTube for tracks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './request/owner-search-req.yaml'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './model/track-summary.yaml'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'
                
  /handle-playlisy/add-track:
    post:
      tags:
        - Handle Playlist
      operationId: addTrack
      summary: Add track to the owned playlist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './request/add-track-req.yaml'
      responses:
        '200':
          description: 'Success'

        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /handle-playlist/add-suggested-track:
    post:
      tags:
        - Handle Playlist
      operationId: addSuggestedTrack
      summary: Add track suggested by the users to the queue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './request/add-existing-track-req.yaml'
      responses:
        '200':
          description: 'Success'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /handle-playlist/add-recommended-track:
    post:
      tags:
        - Handle Playlist
      operationId: addRecommendedTrack
      summary: Add track recommended by the Spotify API to the queue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './request/add-existing-track-req.yaml'
      responses:
        '200':
          description: 'Success'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /handle-playlist/reorder-queue:
    post:
      tags:
        - Handle Playlist
      operationId: reorderQueue
      summary: Reorder the tracks in the queue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: './model/provider-id-list.yaml'
      responses:
        '200':
          description: 'Success'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /handle-playlist/delete-recommendation:
    post:
      tags:
        - Handle Playlist
      operationId: deleteRecommendation
      summary: Delete a tracks from the recommendations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './request/delete-track-req.yaml'
      responses:
        '200':
          description: 'Success'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'


