openapi: '3.0.3'
info:
  title: music-collab-playlist-api
  description: OpenAPI specification for Collaborative music playlist handler
  version: 1.1.0

servers:
  - url: 'http://127.0.0.1:8080'
    description: Local Spring Boot Server

components:
  securitySchemes:
    JSESSIONIDAuth:
      type: apiKey
      in: cookie
      name: JSESSIONID

security:
  - JSESSIONIDAuth: []

paths:
  /api/dashboard:
    get:
      tags:
        - Dashboard
      operationId: getDashboardSettings
      description: get dashboard settings for user
      summary: Get dashboard settings
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './model/dashboard-settings.yaml'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /api/dashboard/name:
    post:
      tags:
        - Dashboard
      operationId: setName
      description: modify suggestion playback settings for user
      summary: Modify suggestion playback settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './request/modify-name-req.yaml'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './response/modify-name-resp.yaml'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /api/dashboard/suggestion-playback:
    post:
      tags:
        - Dashboard
      operationId: setSuggestionPlayback
      description: modify suggestion playback settings for user
      summary: Modify suggestion playback settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './request/modify-suggestion-playback-mode-req.yaml'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './enum/suggestion-playback-mode.yaml'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /api/dashboard/youtube-playback:
    post:
      tags:
        - Dashboard
      operationId: setYoutubePlayback
      description: modify youtube playback settings for user
      summary: Modify youtube playback settings
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './request/modify-youtube-playback-mode-req.yaml'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './enum/youtube-playback-mode.yaml'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /api/dashboard/regenerate-code:
    post:
      tags:
        - Dashboard
      operationId: regenerateDeviceCode
      summary: Regenerate the unique 6-digit device code (server creates new code)
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './response/regenerate-code-resp.yaml'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

  /join-playlist:
    post:
      tags:
        - Join
      operationId: joinPlaylist
      summary: Join a playlist by providing the current playlist name and code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './request/join-playlist-req.yaml'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './response/join-playlist-resp.yaml'
        '400':
          description: 'Bad Request'
          content:
            application/json:
              schema:
                $ref: './error/bad-request.yaml'
        '403':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'
        '404':
          description: 'Not Found'
          content:
            application/json:
              schema:
                $ref: './error/not-found.yaml'

